apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    #nodePort: 30090
    targetPort: 9090
  selector:
    app: prometheus
