apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app: kube-state-metrics
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
    #nodePort: 30080
    targetPort: 8080
  selector:
    app: kube-state-metrics
