apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  #+#selector:
  #+#  matchLabels:
  #+#    app: prometheus
  #+#strategy:
  #+#  rollingUpdate:
  #+#    maxSurge: 1
  #+#    maxUnavailable: 1
  #+#  type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus:v1.4.1
        name: prometheus
        args:
          - -config.file=/etc/prometheus/prometheus.yml
          - -storage.local.path=/prometheus
          - -web.console.libraries=/etc/prometheus/console_libraries
          - -web.console.templates=/etc/prometheus/consoles
          - -storage.local.retention=24h0m0s
          - -storage.local.memory-chunks=500000
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /status
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-volume-config
        - mountPath: /prometheus
          name: prometheus-volume-data
        #+#restartPolicy: Always
        #+#securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: prometheus-volume-config
        configMap:
          name: prometheus-configmap
      - emptyDir: {}
        name: prometheus-volume-data
